### PR TITLE
Fixed wrongly named element

### PR DESCRIPTION
**Pull request by fakob**
This fixes an issue of not being able to change the inverse-02 color.

### CODE REVIEW

**Comment by tw15egan** [comment]
Thank's for catching that!

**Comment by fakob** [comment]
No problem. Do you know when http://themes.carbondesignsystem.com gets this update?

**Comment by tw15egan** [comment]
@fakob  Just deployed the update!

**Comment by fakob** [comment]
Fantastic. Thanks!

**Pull request merged**
